name: NuGet Push

on:
  workflow_call:
    inputs:
      version:
        description: The version of your project, e.g., 1.0.0.
        required: true
        type: string
      environment:
        description: When specified, the environment secret will be used, and not the secret passed from the caller workflow.
        required: false
        type: string
        default: ''
      configuration:
        description: Defines the build configuration. Default is Release.
        required: false
        type: string
        default: 'Release'
      source:
        description: The NuGet source to push the packages to. Default is https://api.nuget.org/v3/index.json.
        required: false
        type: string
        default: 'https://api.nuget.org/v3/index.json'
      download-build-artifact-name:
        description: The name to download the build artifacts. Default, when left empty, is 'format('NuGet-{0}', inputs.configuration)'.
        required: false
        type: string
        default: ''
      verbosity-level:
        description: Sets the verbosity level of the command. Allowed values are quiet, normal and detailed. The default is quiet.
        required: false
        type: string
        default: 'quiet'
      timeout-minutes:
        description: The maximum time in minutes to allow the job to run. Default is 15 minutes.
        required: false
        type: number
        default: 15
    secrets:
      NUGET_TOKEN:
        required: true

jobs:
  deploy:
    if: ${{ inputs.environment == '' }}
    name: 🚀 Deploy v${{ inputs.version }}
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download-build-artifact-name != '' && inputs.download-build-artifact-name || format('NuGet-{0}', inputs.configuration) }}

      - name: List Build Artifacts
        run: |
          pwd
          ls -R
        shell: bash

      - name: Push NuGet Packages
        run: dotnet nuget push '${{ github.workspace }}/*.nupkg' --source ${{ inputs.source }} --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --verbosity ${{ inputs.verbosity-level }}
        shell: bash

  deploy_environment:
    if: ${{ inputs.environment != '' }}
    name: 🚀 Deploy v${{ inputs.version }}
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download-build-artifact-name != '' && inputs.download-build-artifact-name || format('NuGet-{0}', inputs.configuration) }}

      - name: List Build Artifacts
        run: |
          pwd
          ls -R
        shell: bash

      - name: Push NuGet Packages
        run: dotnet nuget push '${{ github.workspace }}/*.nupkg' --source ${{ inputs.source }} --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --verbosity ${{ inputs.verbosity-level }}
        shell: bash
